//! CuriosityEngine -- автономное любопытство на основе неопределённостей в графе.
//!
//! Engine сканирует граф на маркеры неопределённости и генерирует задачи для исследования.
//!
//! Типы маркеров:
//! - ConfidenceLow: связь с низким confidence (< 0.5)
//! - EffectMissing: Cause без исходящих Effect-связей
//! - CauseMissing: Effect без входящих Cause-связей (сильный триггер)
//! - Contradiction: противоречие в связях (A→B и B→A оба leads_to)

use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::sync::RwLock;
use uuid::Uuid;

use crate::graph::{Edge, NodeId, EdgeId, NodeType, Relation};

use super::{Actor, L2Actor};

/// Тип неопределённости
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum UncertaintyType {
    ConfidenceLow,
    EffectMissing,
    CauseMissing,
    Contradiction,
}

/// Маркер неопределённости в графе
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UncertaintyMarker {
    pub id: String,
    pub node_id: NodeId,
    pub edge_id: Option<EdgeId>,
    pub uncertainty_type: UncertaintyType,
    /// Сила триггера (0.0-1.0) — чем выше, тем важнее исследовать
    pub strength: f32,
    pub description: String,
}

impl UncertaintyMarker {
    pub fn new(
        node_id: NodeId,
        edge_id: Option<EdgeId>,
        uncertainty_type: UncertaintyType,
        strength: f32,
        description: String,
    ) -> Self {
        Self {
            id: format!("unc_{}", Uuid::new_v4().to_string().replace("-", "")),
            node_id,
            edge_id,
            uncertainty_type,
            strength,
            description,
        }
    }
}

/// Задача для исследования (generated by CuriosityEngine)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CuriosityTask {
    pub id: String,
    pub marker_id: String,
    pub priority: f32,
    pub description: String,
    pub status: TaskStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TaskStatus {
    Pending,
    InProgress,
    Completed,
    Abandoned,
}

impl CuriosityTask {
    pub fn new(marker: &UncertaintyMarker) -> Self {
        Self {
            id: format!("task_{}", Uuid::new_v4().to_string().replace("-", "")),
            marker_id: marker.id.clone(),
            priority: marker.strength,
            description: format!("Исследовать: {}", marker.description),
            status: TaskStatus::Pending,
        }
    }
}

/// Эмоциональное состояние агента (на основе irritation metric)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum EmotionalState {
    /// Irritation < 0.3: спокойное состояние
    Calm,
    /// 0.3 <= Irritation < 0.6: лёгкое любопытство
    Curious,
    /// 0.6 <= Irritation < 0.8: раздражение, нужно исследовать
    Irritated,
    /// Irritation >= 0.8: критическое состояние, срочное исследование
    Distressed,
}

impl EmotionalState {
    pub fn from_irritation(score: f32) -> Self {
        if score < 0.3 {
            EmotionalState::Calm
        } else if score < 0.6 {
            EmotionalState::Curious
        } else if score < 0.8 {
            EmotionalState::Irritated
        } else {
            EmotionalState::Distressed
        }
    }
}

/// CuriosityEngine: автономное любопытство на основе неопределённостей
pub struct CuriosityEngine {
    /// Источник графа — общий backend через L2Actor (раньше был отдельный in-memory
    /// `Graph`, который наполнялся только по gRPC → на MCP-контуре пуст, irritation=0).
    l2: Arc<L2Actor>,
    /// Порог для генерации задач (задачи с priority < threshold не создаются)
    task_threshold: f32,
    /// Кэш маркеров неопределённости
    markers_cache: RwLock<HashMap<String, UncertaintyMarker>>,
    /// Активные задачи
    active_tasks: RwLock<HashMap<String, CuriosityTask>>,
}

impl CuriosityEngine {
    pub fn new(l2: Arc<L2Actor>, task_threshold: f32) -> Self {
        Self {
            l2,
            task_threshold,
            markers_cache: RwLock::new(HashMap::new()),
            active_tasks: RwLock::new(HashMap::new()),
        }
    }

    /// Создать CuriosityEngine с порогом по умолчанию (0.3)
    pub fn with_default_threshold(l2: Arc<L2Actor>) -> Self {
        Self::new(l2, 0.3)
    }

    /// Сканировать граф на маркеры неопределённости.
    /// Читаем весь граф из backend один раз и строим смежность в памяти
    /// (чтобы не делать O(N·E) сканов), затем те же 3 проверки, что и раньше.
    pub async fn scan_uncertainties(&self) -> Vec<UncertaintyMarker> {
        let mut markers = Vec::new();
        let nodes = self.l2.list_all_nodes().await.unwrap_or_default();
        let edges = self.l2.list_all_edges().await.unwrap_or_default();

        // Смежность: source → рёбра, target → рёбра
        let mut out_map: HashMap<String, Vec<&Edge>> = HashMap::new();
        let mut in_map: HashMap<String, Vec<&Edge>> = HashMap::new();
        for e in &edges {
            out_map.entry(e.source.0.clone()).or_default().push(e);
            in_map.entry(e.target.0.clone()).or_default().push(e);
        }

        // 2. EffectMissing: Cause без исходящих LeadsTo
        for node in &nodes {
            if matches!(node.node_type, NodeType::Cause) {
                let has_effect = out_map
                    .get(&node.id.0)
                    .map(|es| es.iter().any(|e| matches!(e.relation, Relation::LeadsTo)))
                    .unwrap_or(false);
                if !has_effect {
                    markers.push(UncertaintyMarker::new(
                        node.id.clone(),
                        None,
                        UncertaintyType::EffectMissing,
                        0.6,
                        format!("Cause '{}' не приводит к известному эффекту", node.content),
                    ));
                }
            }
        }

        // 3. CauseMissing: Effect без входящих LeadsTo
        for node in &nodes {
            if matches!(node.node_type, NodeType::Effect) {
                let has_cause = in_map
                    .get(&node.id.0)
                    .map(|es| es.iter().any(|e| matches!(e.relation, Relation::LeadsTo)))
                    .unwrap_or(false);
                if !has_cause {
                    markers.push(UncertaintyMarker::new(
                        node.id.clone(),
                        None,
                        UncertaintyType::CauseMissing,
                        0.8,
                        format!("Effect '{}' не имеет известной причины", node.content),
                    ));
                }
            }
        }

        // 4. Contradiction: A→B и B→A (оба LeadsTo)
        for e_a in &edges {
            if !matches!(e_a.relation, Relation::LeadsTo) {
                continue;
            }
            if let Some(back) = out_map.get(&e_a.target.0) {
                for e_b in back {
                    if e_b.target == e_a.source
                        && matches!(e_b.relation, Relation::LeadsTo)
                        && e_b.id != e_a.id
                    {
                        markers.push(UncertaintyMarker::new(
                            e_a.source.clone(),
                            Some(e_a.id.clone()),
                            UncertaintyType::Contradiction,
                            0.9,
                            format!(
                                "Противоречие: {}→{} и {}→{}",
                                e_a.source.0, e_a.target.0, e_b.source.0, e_b.target.0
                            ),
                        ));
                    }
                }
            }
        }

        // Кэшируем маркеры
        let mut cache = self.markers_cache.write().await;
        for marker in &markers {
            cache.insert(marker.id.clone(), marker.clone());
        }
        drop(cache);

        markers
    }

    /// Приоритизировать и сгенерировать exploration tasks
    pub async fn generate_tasks(&self) -> Vec<CuriosityTask> {
        let markers = self.scan_uncertainties().await;
        let mut tasks = Vec::new();

        for marker in markers {
            if marker.strength >= self.task_threshold {
                let task = CuriosityTask::new(&marker);
                tasks.push(task.clone());
                
                // Сохраняем в active_tasks
                self.active_tasks.write().await.insert(task.id.clone(), task);
            }
        }

        // Сортируем по приоритету (убывание)
        tasks.sort_by(|a, b| b.priority.partial_cmp(&a.priority).unwrap_or(std::cmp::Ordering::Equal));

        tasks
    }

    /// Рассчитать Irritation Metric (0.0–1.0)
    pub async fn irritation_score(&self) -> f32 {
        let markers = self.scan_uncertainties().await;
        
        if markers.is_empty() {
            return 0.0;
        }

        // Различные подходы к расчёту:
        // 1. Средняя сила всех маркеров
        let avg_strength: f32 = markers.iter().map(|m| m.strength).sum::<f32>() / markers.len() as f32;
        
        // 2. Максимальная сила (самый раздражающий маркер)
        let max_strength = markers.iter().map(|m| m.strength).fold(0.0f32, f32::max);
        
        // 3. Weighted score: больше маркеров = выше раздражение
        let count_factor = markers.len() as f32 / 10.0; // нормализуем до 1.0
        let count_factor = if count_factor > 1.0 { 1.0 } else { count_factor };
        
        // Комбинированный score: 0.4 * avg + 0.4 * max + 0.2 * count_factor
        let score = 0.4 * avg_strength + 0.4 * max_strength + 0.2 * count_factor;
        
        if score > 1.0 { 1.0 } else { score } // Ограничиваем до 1.0
    }

    /// Определить эмоциональное состояние
    pub async fn emotional_state(&self) -> EmotionalState {
        let score = self.irritation_score().await;
        EmotionalState::from_irritation(score)
    }

    /// Получить активные задачи
    pub async fn get_active_tasks(&self) -> Vec<CuriosityTask> {
        self.active_tasks.read().await.values().cloned().collect()
    }

    /// Завершить задачу
    pub async fn complete_task(&self, task_id: &str) -> bool {
        let mut tasks = self.active_tasks.write().await;
        if let Some(task) = tasks.get_mut(task_id) {
            task.status = TaskStatus::Completed;
            true
        } else {
            false
        }
    }

    /// Удалить задачу
    pub async fn abandon_task(&self, task_id: &str) -> bool {
        let mut tasks = self.active_tasks.write().await;
        tasks.remove(task_id).is_some()
    }

    /// Получить отчёт о состоянии CuriosityEngine
    pub async fn get_report(&self) -> CuriosityReport {
        let markers = self.scan_uncertainties().await;
        let irritation = self.irritation_score().await;
        let state = self.emotional_state().await;
        let active_tasks = self.get_active_tasks().await;

        CuriosityReport {
            total_markers: markers.len(),
            markers_by_type: self.count_markers_by_type(&markers),
            irritation_score: irritation,
            emotional_state: format!("{:?}", state),
            active_tasks: active_tasks.len(),
            pending_tasks: active_tasks.iter().filter(|t| t.status == TaskStatus::Pending).count(),
        }
    }

    fn count_markers_by_type(&self, markers: &[UncertaintyMarker]) -> HashMap<String, usize> {
        let mut counts = HashMap::new();
        for marker in markers {
            let type_name = format!("{:?}", marker.uncertainty_type);
            *counts.entry(type_name).or_insert(0) += 1;
        }
        counts
    }
}

/// Отчёт о состоянии CuriosityEngine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CuriosityReport {
    pub total_markers: usize,
    pub markers_by_type: HashMap<String, usize>,
    pub irritation_score: f32,
    pub emotional_state: String,
    pub active_tasks: usize,
    pub pending_tasks: usize,
}

#[async_trait]
impl Actor for CuriosityEngine {
    fn name(&self) -> &str {
        "CuriosityEngine"
    }

    async fn size(&self) -> usize {
        self.markers_cache.read().await.len() + self.active_tasks.read().await.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::{Node, NodeType};
    use crate::persistence::InMemoryBackend;

    async fn empty_l2() -> Arc<L2Actor> {
        Arc::new(L2Actor::new(Arc::new(InMemoryBackend::new())))
    }

    async fn l2_with_cause() -> Arc<L2Actor> {
        let l2 = empty_l2().await;
        l2.add_node(&Node::new(NodeType::Cause, "Test cause without effect"))
            .await
            .unwrap();
        l2
    }

    #[tokio::test]
    async fn test_irritation_score_empty() {
        let engine = CuriosityEngine::with_default_threshold(empty_l2().await);
        assert_eq!(engine.irritation_score().await, 0.0);
    }

    #[tokio::test]
    async fn test_emotional_state_calm() {
        let engine = CuriosityEngine::with_default_threshold(empty_l2().await);
        assert_eq!(engine.emotional_state().await, EmotionalState::Calm);
    }

    #[tokio::test]
    async fn test_scan_effect_missing() {
        let engine = CuriosityEngine::with_default_threshold(l2_with_cause().await);
        let markers = engine.scan_uncertainties().await;
        assert!(markers
            .iter()
            .any(|m| m.uncertainty_type == UncertaintyType::EffectMissing));
    }

    #[tokio::test]
    async fn test_generate_tasks_with_threshold() {
        let engine = CuriosityEngine::with_default_threshold(l2_with_cause().await);
        let tasks = engine.generate_tasks().await;
        assert!(!tasks.is_empty());
        assert!(tasks[0].priority >= 0.3);
    }

    #[tokio::test]
    async fn test_get_report() {
        let engine = CuriosityEngine::with_default_threshold(empty_l2().await);
        let report = engine.get_report().await;
        assert_eq!(report.total_markers, 0);
        assert_eq!(report.irritation_score, 0.0);
        assert_eq!(report.emotional_state, "Calm");
        assert_eq!(report.active_tasks, 0);
    }

    #[tokio::test]
    async fn test_task_lifecycle() {
        let engine = CuriosityEngine::with_default_threshold(l2_with_cause().await);
        let tasks = engine.generate_tasks().await;
        assert!(!tasks.is_empty());
        let task_id = tasks[0].id.clone();
        let active = engine.get_active_tasks().await;
        assert!(active.iter().any(|t| t.id == task_id));
        assert!(engine.complete_task(&task_id).await);
        let active = engine.get_active_tasks().await;
        let completed = active.iter().find(|t| t.id == task_id).unwrap();
        assert_eq!(completed.status, TaskStatus::Completed);
    }
}
